name: permit-management

services:
  backend:
    restart: always
    image: ghcr.io/permit-management/backend:main
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./configs/config.yml:/app/config.yml
    environment:
      APP_RUNMODE: release
      APP_HTTPPORT: 8080
      APP_SERVERKEY: SecretKey
      APP_LISTEN: 0.0.0.0
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: permit_user
      DATABASE_PASSWORD: ZXcvbnm123!
      DATABASE_DBNAME: permit_management
      GOOSE_DRIVER: mysql
      GOOSE_DBSTRING: permit_user:ZXcvbnm123!@tcp(db:3306)/permit_management?charset=utf8mb4&parseTime=True&loc=UTC
      GOOSE_MIGRATION_DIR: ./db/migrations
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:8080"
    networks:
      - permit_network
    entrypoint:
      [
        "/app/scripts/startup/wait-for.sh",
        "${DB_HOST:-db}:${DB_PORT:-3306}",
        "--",
        "/app/runner"
      ]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ZXcvbnm123!
      MYSQL_DATABASE: permit_management
      MYSQL_USER: permit_user
      MYSQL_PASSWORD: ZXcvbnm123!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - permit_network


volumes:
  db_data:
  
networks:
  permit_network:
    name: permit_network
    driver: bridge
 