name: permit-management

services:
  user-ms:
    image: permit-backend:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT:-8080}:8080
    environment:
      APP_ENV: ${APP_ENV:-debug}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-SIMFAST_DEV}
      DB_USERNAME: ${DB_USERNAME:-SIMFAST_USER}
      DB_PASSWORD: ${DB_PASSWORD:-SIMFAST_PASS}
      DB_SCHEMA: ${DB_SCHEMA:-user_schema}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - permit_network
    volumes:
      - ./config.yml:/app/config.yml
    entrypoint:
      [
        "/app/scripts/startup/wait-for.sh",
        "${DB_HOST:-db}:${DB_PORT:-5432}",
        "--",
        "/app/runner",
        "serve"
      ]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ZXcvbnm123!
      MYSQL_DATABASE: permit_management
      MYSQL_USER: permit_user
      MYSQL_PASSWORD: ZXcvbnm123!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - permit_network


volumes:
  db_data:
  
networks:
  permit_network:
    name: permit_network
    driver: bridge
 